import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'The terms and conditions governing your use of TrendPulse AI.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <div className="border-b bg-muted/40">
        <div className="container mx-auto px-4 lg:px-6 py-12">
          <h1 className="text-4xl font-bold tracking-tight">Terms of Service</h1>
          <p className="mt-2 text-muted-foreground">Last updated: January 1, 2025</p>
        </div>
      </div>
      <div className="container mx-auto px-4 lg:px-6 py-12 max-w-4xl">
        <div className="space-y-8">

          <section>
            <h2 className="text-xl font-bold mb-3">1. Acceptance of Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              By accessing or using TrendPulse AI (&ldquo;the Service&rdquo;), you agree to be bound by these Terms of Service. If you do not agree to these terms, you may not use the Service. These Terms apply to all users of the Service, including those who contribute content, information, or other materials.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">2. Description of Service</h2>
            <p className="text-muted-foreground leading-relaxed">
              TrendPulse AI provides a competitive intelligence platform that allows users to track competitors, generate AI-powered audit reports, and create data-driven strategies. The Service uses third-party AI providers (including Google Gemini) to process and analyze content submitted by users.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">3. Account Registration</h2>
            <p className="text-muted-foreground leading-relaxed">
              To use certain features of the Service, you must register for an account. You agree to provide accurate, current, and complete information during registration and to update such information to keep it accurate. You are responsible for all activity that occurs under your account. You must notify us immediately of any unauthorized use of your account.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">4. Acceptable Use</h2>
            <p className="text-muted-foreground leading-relaxed mb-3">You agree not to use the Service to:</p>
            <ul className="list-disc list-inside text-muted-foreground space-y-1.5">
              <li>Violate any applicable laws or regulations</li>
              <li>Upload documents containing personally identifiable information of third parties without consent</li>
              <li>Reverse engineer, decompile, or attempt to extract the source code of our platform</li>
              <li>Automate excessive requests in a manner that degrades service performance</li>
              <li>Use the Service for any unlawful purpose or in any way that could harm others</li>
              <li>Impersonate any person or entity or misrepresent your affiliation</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">5. Intellectual Property</h2>
            <p className="text-muted-foreground leading-relaxed">
              The Service and its original content (excluding content uploaded by users) are and will remain the exclusive property of TrendPulse AI. You retain ownership of any content you submit through the Service, but grant TrendPulse AI a limited license to process and store that content solely to provide the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">6. AI-Generated Content</h2>
            <p className="text-muted-foreground leading-relaxed">
              AI-generated insights, audits, and strategies are provided for informational purposes only. They do not constitute professional business, legal, or financial advice. You are solely responsible for any business decisions you make based on content generated by the Service. AI outputs may contain errors, and you should verify critical information independently.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">7. Limitation of Liability</h2>
            <p className="text-muted-foreground leading-relaxed">
              To the maximum extent permitted by applicable law, TrendPulse AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, or goodwill, arising out of or in connection with your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">8. Termination</h2>
            <p className="text-muted-foreground leading-relaxed">
              We reserve the right to suspend or terminate your account at our discretion, with or without notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties. Upon termination, your right to use the Service immediately ceases.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">9. Changes to Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              We may modify these Terms at any time. We will notify you of significant changes via email or a prominent notice within the Service. Your continued use of the Service after the effective date of the revised Terms constitutes your acceptance of those changes.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">10. Contact</h2>
            <p className="text-muted-foreground leading-relaxed">
              Questions about these Terms? Contact us at{' '}
              <a href="mailto:legal@trendpulse.ai" className="text-primary hover:underline">
                legal@trendpulse.ai
              </a>.
            </p>
          </section>

        </div>
      </div>
    </div>
  );
}
